# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0075_auto_20201119_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengequestionnaire',
            name='answ_eight',
        ),
        migrations.RemoveField(
            model_name='challengequestionnaire',
            name='answ_five',
        ),
        migrations.RemoveField(
            model_name='challengequestionnaire',
            name='answ_four',
        ),
        migrations.RemoveField(
            model_name='challengequestionnaire',
            name='answ_nine',
        ),
        migrations.RemoveField(
            model_name='challengequestionnaire',
            name='answ_one',
        ),
        migrations.RemoveField(
            model_name='challengequestionnaire',
            name='answ_seven',
        ),
        migrations.RemoveField(
            model_name='challengequestionnaire',
            name='answ_six',
        ),
        migrations.RemoveField(
            model_name='challengequestionnaire',
            name='answ_ten',
        ),
        migrations.RemoveField(
            model_name='challengequestionnaire',
            name='answ_three',
        ),
        migrations.RemoveField(
            model_name='challengequestionnaire',
            name='answ_two',
        ),
        migrations.RemoveField(
            model_name='challengequestionnaire',
            name='is_answered',
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_10',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_11',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_12',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_13',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_14',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_15',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_16',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_17',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_18',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_19',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_20',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_21',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_22',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_23',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_24',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_25',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_26',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_27',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_28',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_29',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_30',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_31',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_32',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_33',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_34',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_35',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_36',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_37',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_38',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_39',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_6',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_7',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_8',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='challengequestionnaire',
            name='a_9',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
